permalink: pretty

title: Stanford Software Research Lunch
tagline: ""
url: https://software-research-lunch.github.io
baseurl: ""

sass:
  sass_dir: _sass
  style: :compressed

analytics_id: UA-80843812-2

github:
  repo: https://github.com/software-research-lunch/software-research-lunch.github.io

exclude: [
  README.md,
  Makefile,
  PAST_ORDERS.md,
  000.yml
]
